name: My First GitHub Actions Workflow
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a diagnostic message
        run: echo "The environment is spinning up successfully!"

      - name: Run code compilation simulation
        run: |
          echo "Compiling code..."
          echo "All unit tests passed successfully!"
  
